// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import "./globals.css";

export const metadata = {
  title: "P2PShare — Encrypted File Transfer",
  description: "Peer-to-peer encrypted file sharing and chat. No servers store your data.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* CryptoJS — needed for AES chunk encryption in the browser */}
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js"
          integrity="sha512-a+SUDuwNzXDvz4XrIcXHuCf089/iJAoLskI3A5Yiqz9zygH11fFFa7QscAnwB4q8L7YmuRpBLBxAplm2QACmA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
